# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ecf8b84847a9d20dcfcf7185d1ca58a4d88a3a6add1c95f7c03753fa692f3fd7fb1a5fc2c2fcb20debdcf506267d31f4ed4181ce3037dc2a53edb54feeb484

test:
  secret_key_base: 32583b8c0b1849d7aefdb358ed6913ffc23372ad9edf9a39c88ebb0c0d9cd857f46adc1c01a26be4764d5524d0a3ea5dcd5f7627f7b0a4c5239bef26bcfadc30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
